//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACREDITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACREDITACION()
        {
            this.ITEMACREDITACION = new HashSet<ITEMACREDITACION>();
        }
    
        public int ID { get; set; }
        public string TRABAJADOR { get; set; }
        public string EMPRESACONTRATO { get; set; }
        public Nullable<int> EMPRESAMANDANTE { get; set; }
        public int ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual MANDANTE MANDANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMACREDITACION> ITEMACREDITACION { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
