//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANEXOSPENDIENTES
    {
        public string EMPRESA { get; set; }
        public string PERSONA { get; set; }
        public int CONTRATO { get; set; }
        public byte[] PDF { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<bool> FIRMATRABAJADOR { get; set; }
        public Nullable<bool> FIRMAEMPRESA { get; set; }
    }
}
