//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATENCIONORGANIZACIONALONLINE
    {
        public int ID { get; set; }
        public string TRABAJADOR { get; set; }
        public System.DateTime FECHASOLICITUD { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> FECHARESPUESTA { get; set; }
        public string CONSULTA { get; set; }
        public string RESOLUCION { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
