//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANCOEMPRESA
    {
        public string EMPRESA { get; set; }
        public int BANCO { get; set; }
        public int NCUENTA { get; set; }
        public int TCUENTA { get; set; }
    
        public virtual BANCO BANCO1 { get; set; }
        public virtual EMPRESA EMPRESA1 { get; set; }
    }
}
