//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICACION
    {
        public int ID { get; set; }
        public byte[] CONTRATOS { get; set; }
        public byte[] ANEXOS { get; set; }
        public byte[] FINIQUITOS { get; set; }
        public byte[] LIQUIDACIONES { get; set; }
        public byte[] LIBRO { get; set; }
        public byte[] IMPOSICIONES { get; set; }
        public byte[] PARAMETRO { get; set; }
        public byte[] DECLARACION_VIGENTE { get; set; }
        public byte[] DECLARACION_FINIQUITOS { get; set; }
        public byte[] AFC { get; set; }
        public byte[] COMPROBANTES_PAGO { get; set; }
        public byte[] LIBRO_REMUNERACIONES { get; set; }
        public byte[] CERTIFICADO { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHA_CERTIFICADO { get; set; }
        public int FAENA { get; set; }
        public int ESTADO { get; set; }
        public string CONTRATOSEXT { get; set; }
        public string ANEXOSEXT { get; set; }
        public string FINIQUITOSEXT { get; set; }
        public string LIQUIDACIONESEXT { get; set; }
        public string LIBROEXT { get; set; }
        public string IMPOSICIONESEXT { get; set; }
        public string PARAMETROEXT { get; set; }
        public string DECLARACION_VIGENTEEXT { get; set; }
        public string DECLARACION_FINIQUITOEXT { get; set; }
        public string AFCEXT { get; set; }
        public string COMPROBANTES_PAGOEXT { get; set; }
        public string LIBRO_REMUNERACIONESEXT { get; set; }
        public string CERTIFICADOEXT { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual FAENA FAENA1 { get; set; }
    }
}
