//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICADOVIEW
    {
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public byte[] CERTIFICADO { get; set; }
        public int ESTADO { get; set; }
        public string CERTIFICADOEXT { get; set; }
        public string OBSERVACION { get; set; }
        public int ID { get; set; }
        public int FAENA { get; set; }
    }
}
