//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLACIONESDIARIAS
    {
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public int CANTIDAD { get; set; }
        public string EMPRESA { get; set; }
        public int FAENA { get; set; }
        public string EMPRESA_ALIMENTACION { get; set; }
        public int DOTACION_DIARIA { get; set; }
    
        public virtual EMPRESA EMPRESA1 { get; set; }
        public virtual FAENA FAENA1 { get; set; }
    }
}
