//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbgycEntities3 : DbContext
    {
        public dbgycEntities3()
            : base("name=dbgycEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AREA> AREA { get; set; }
        public virtual DbSet<BANCO> BANCO { get; set; }
        public virtual DbSet<BANCOEMPRESA> BANCOEMPRESA { get; set; }
        public virtual DbSet<CALIBRACIONEQUIPOS> CALIBRACIONEQUIPOS { get; set; }
        public virtual DbSet<CARGO> CARGO { get; set; }
        public virtual DbSet<CARGOEMPRESA> CARGOEMPRESA { get; set; }
        public virtual DbSet<CARROCERIA> CARROCERIA { get; set; }
        public virtual DbSet<CCOSTO> CCOSTO { get; set; }
        public virtual DbSet<CHARLASEGURIDAD> CHARLASEGURIDAD { get; set; }
        public virtual DbSet<CIUDAD> CIUDAD { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<COMUNA> COMUNA { get; set; }
        public virtual DbSet<DESCBATERIAEXAMENES> DESCBATERIAEXAMENES { get; set; }
        public virtual DbSet<DESCPERMISO> DESCPERMISO { get; set; }
        public virtual DbSet<DESCUENTOHABERCONTRATO> DESCUENTOHABERCONTRATO { get; set; }
        public virtual DbSet<DESCUENTOSHABERES> DESCUENTOSHABERES { get; set; }
        public virtual DbSet<DESCVALIDACION> DESCVALIDACION { get; set; }
        public virtual DbSet<ECIVIL> ECIVIL { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<ESPECIALIDAD> ESPECIALIDAD { get; set; }
        public virtual DbSet<EXAMENMEDICO> EXAMENMEDICO { get; set; }
        public virtual DbSet<FORMHEXTRA> FORMHEXTRA { get; set; }
        public virtual DbSet<IMPUNICO> IMPUNICO { get; set; }
        public virtual DbSet<INSTALACIONES> INSTALACIONES { get; set; }
        public virtual DbSet<INSTITUCION> INSTITUCION { get; set; }
        public virtual DbSet<LIMPIEZABANHOS> LIMPIEZABANHOS { get; set; }
        public virtual DbSet<MANDANTE> MANDANTE { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<MODELO> MODELO { get; set; }
        public virtual DbSet<NACIONALIDAD> NACIONALIDAD { get; set; }
        public virtual DbSet<NOTAS> NOTAS { get; set; }
        public virtual DbSet<PERMISO> PERMISO { get; set; }
        public virtual DbSet<PREVISION> PREVISION { get; set; }
        public virtual DbSet<REGION> REGION { get; set; }
        public virtual DbSet<REGISTRORELOJ> REGISTRORELOJ { get; set; }
        public virtual DbSet<REMUNERACION> REMUNERACION { get; set; }
        public virtual DbSet<SALUD> SALUD { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<SOLICITUDSERVICIO> SOLICITUDSERVICIO { get; set; }
        public virtual DbSet<TIPOCONTRATO> TIPOCONTRATO { get; set; }
        public virtual DbSet<TIPOCUENTA> TIPOCUENTA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VALIDACIONES> VALIDACIONES { get; set; }
        public virtual DbSet<VEHICULO> VEHICULO { get; set; }
        public virtual DbSet<MARCACIONRELOJ> MARCACIONRELOJ { get; set; }
        public virtual DbSet<PERMISOINASISTENCIA> PERMISOINASISTENCIA { get; set; }
        public virtual DbSet<SOLICITUDPERMANENTESERVICIO> SOLICITUDPERMANENTESERVICIO { get; set; }
        public virtual DbSet<RESUMENCONTRATAPROFESIONAL> RESUMENCONTRATAPROFESIONAL { get; set; }
        public virtual DbSet<ACREDITACION> ACREDITACION { get; set; }
        public virtual DbSet<ENROLL> ENROLL { get; set; }
        public virtual DbSet<GESTIONORGANIZACIONAL> GESTIONORGANIZACIONAL { get; set; }
        public virtual DbSet<GRUPOFAMILIAR> GRUPOFAMILIAR { get; set; }
        public virtual DbSet<ITEMACREDITACION> ITEMACREDITACION { get; set; }
        public virtual DbSet<LOGINTRABAJADOR> LOGINTRABAJADOR { get; set; }
        public virtual DbSet<TRABAJADORESNOACREDITADOS> TRABAJADORESNOACREDITADOS { get; set; }
        public virtual DbSet<ESCALASUELDOS> ESCALASUELDOS { get; set; }
        public virtual DbSet<NOTIFICACION> NOTIFICACION { get; set; }
        public virtual DbSet<OTROSERVICIO> OTROSERVICIO { get; set; }
        public virtual DbSet<CARTAAMONESTACION> CARTAAMONESTACION { get; set; }
        public virtual DbSet<COLACIONESHHEE> COLACIONESHHEE { get; set; }
        public virtual DbSet<MOVILIZACIONHHEE> MOVILIZACIONHHEE { get; set; }
        public virtual DbSet<ACREDITAVEHICULO> ACREDITAVEHICULO { get; set; }
        public virtual DbSet<ACTEXTRAPROGRAMATICA> ACTEXTRAPROGRAMATICA { get; set; }
        public virtual DbSet<TRABAJADORCONTRATO> TRABAJADORCONTRATO { get; set; }
        public virtual DbSet<ANEXOSPENDIENTES> ANEXOSPENDIENTES { get; set; }
        public virtual DbSet<HHEE> HHEE { get; set; }
        public virtual DbSet<SOLICITUDHHEE> SOLICITUDHHEE { get; set; }
        public virtual DbSet<ATENCIONORGANIZACIONAL> ATENCIONORGANIZACIONAL { get; set; }
        public virtual DbSet<ATENCIONORGANIZACIONALONLINE> ATENCIONORGANIZACIONALONLINE { get; set; }
        public virtual DbSet<DECMATERIA> DECMATERIA { get; set; }
        public virtual DbSet<ENVIOMAIL> ENVIOMAIL { get; set; }
        public virtual DbSet<SETUPMANDANTE> SETUPMANDANTE { get; set; }
        public virtual DbSet<HHEEPORFAENA> HHEEPORFAENA { get; set; }
        public virtual DbSet<NOTICIA> NOTICIA { get; set; }
        public virtual DbSet<SERVICIOEMPRESA> SERVICIOEMPRESA { get; set; }
        public virtual DbSet<BUSCADORTRABAJADORES> BUSCADORTRABAJADORES { get; set; }
        public virtual DbSet<PANORAMA> PANORAMA { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
        public virtual DbSet<TURNOCOLACION> TURNOCOLACION { get; set; }
        public virtual DbSet<ABASTECIMIENTOAGUA> ABASTECIMIENTOAGUA { get; set; }
        public virtual DbSet<MANOOBRADIRECTA> MANOOBRADIRECTA { get; set; }
        public virtual DbSet<SOLICITUDANEXO> SOLICITUDANEXO { get; set; }
        public virtual DbSet<EPP> EPP { get; set; }
        public virtual DbSet<CONTRATADIRECTA> CONTRATADIRECTA { get; set; }
        public virtual DbSet<CONTRATAPROFESIONAL> CONTRATAPROFESIONAL { get; set; }
        public virtual DbSet<VACACIONES> VACACIONES { get; set; }
        public virtual DbSet<SERVICIOCONTRATADO> SERVICIOCONTRATADO { get; set; }
        public virtual DbSet<TIPOLICENCIASMEDICAS> TIPOLICENCIASMEDICAS { get; set; }
        public virtual DbSet<TIPOMEDICO> TIPOMEDICO { get; set; }
        public virtual DbSet<LICENCIAMEDICA> LICENCIAMEDICA { get; set; }
        public virtual DbSet<DESGLOSEVACACION> DESGLOSEVACACION { get; set; }
        public virtual DbSet<TIPOVACACION> TIPOVACACION { get; set; }
        public virtual DbSet<SOLICITUDVACACIONES> SOLICITUDVACACIONES { get; set; }
        public virtual DbSet<CERTIFICACIONUPDATE> CERTIFICACIONUPDATE { get; set; }
        public virtual DbSet<CERTIFICACION> CERTIFICACION { get; set; }
        public virtual DbSet<CERTIFICADOVIEW> CERTIFICADOVIEW { get; set; }
        public virtual DbSet<DIASCOMPENSADOS> DIASCOMPENSADOS { get; set; }
        public virtual DbSet<PARAMETRODIACOMPENSADO> PARAMETRODIACOMPENSADO { get; set; }
        public virtual DbSet<SOLICITUDPERMISOINASISTENCIA> SOLICITUDPERMISOINASISTENCIA { get; set; }
        public virtual DbSet<COMPENSADO_UTILIZADO> COMPENSADO_UTILIZADO { get; set; }
        public virtual DbSet<COLACIONESDIARIAS> COLACIONESDIARIAS { get; set; }
        public virtual DbSet<LOG_MARCACIONES> LOG_MARCACIONES { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<ARCHIVOS_ERROR> ARCHIVOS_ERROR { get; set; }
        public virtual DbSet<LOG_ACCESO> LOG_ACCESO { get; set; }
        public virtual DbSet<FINIQUITO> FINIQUITO { get; set; }
        public virtual DbSet<DOCUMENTOS_CLOUD> DOCUMENTOS_CLOUD { get; set; }
        public virtual DbSet<FAENA> FAENA { get; set; }
        public virtual DbSet<TIPO_BUCKET> TIPO_BUCKET { get; set; }
        public virtual DbSet<CONTRATO> CONTRATO { get; set; }
        public virtual DbSet<JORNADA> JORNADA { get; set; }
        public virtual DbSet<ARCHIVOS_EMPRESA> ARCHIVOS_EMPRESA { get; set; }
        public virtual DbSet<PERMISO_V2> PERMISO_V2 { get; set; }
        public virtual DbSet<MARCACIONyRUT> MARCACIONyRUT { get; set; }
        public virtual DbSet<LOG_DOCUMENTOS_VALIDACION> LOG_DOCUMENTOS_VALIDACION { get; set; }
        public virtual DbSet<HASH_DOCUMENTOS> HASH_DOCUMENTOS { get; set; }
        public virtual DbSet<TRABAJADORCONTRATONUEVO> TRABAJADORCONTRATONUEVO { get; set; }
        public virtual DbSet<ANEXOS> ANEXOS { get; set; }
        public virtual DbSet<LOG_ACEPTATIEMPO> LOG_ACEPTATIEMPO { get; set; }
        public virtual DbSet<rhuedias> rhuedias { get; set; }
        public virtual DbSet<FERIADO> FERIADO { get; set; }
        public virtual DbSet<remecarg> remecarg { get; set; }
        public virtual DbSet<remedesc> remedesc { get; set; }
        public virtual DbSet<remehabe> remehabe { get; set; }
        public virtual DbSet<remepage> remepage { get; set; }
        public virtual DbSet<remepara> remepara { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<TurnoDetalle> TurnoDetalle { get; set; }
        public virtual DbSet<TurnoTrabajador> TurnoTrabajador { get; set; }
        public virtual DbSet<rhueperi> rhueperi { get; set; }
        public virtual DbSet<rhuesolc> rhuesolc { get; set; }
        public virtual DbSet<rhuesolv> rhuesolv { get; set; }
        public virtual DbSet<rhueusos> rhueusos { get; set; }
        public virtual DbSet<remeasis> remeasis { get; set; }
        public virtual DbSet<remebanc> remebanc { get; set; }
        public virtual DbSet<remebene> remebene { get; set; }
        public virtual DbSet<remecenr> remecenr { get; set; }
        public virtual DbSet<remedein> remedein { get; set; }
        public virtual DbSet<remefami> remefami { get; set; }
        public virtual DbSet<remehain> remehain { get; set; }
        public virtual DbSet<remeinst> remeinst { get; set; }
        public virtual DbSet<remelabo> remelabo { get; set; }
        public virtual DbSet<remepers> remepers { get; set; }
        public virtual DbSet<remeproc> remeproc { get; set; }
        public virtual DbSet<remeresu> remeresu { get; set; }
        public virtual DbSet<rhueempr> rhueempr { get; set; }
        public virtual DbSet<remebita> remebita { get; set; }
        public virtual DbSet<FERIADOESPECIAL> FERIADOESPECIAL { get; set; }
        public virtual DbSet<SINDICATOTRABAJADOR> SINDICATOTRABAJADOR { get; set; }
        public virtual DbSet<PERFILTRABAJADOR> PERFILTRABAJADOR { get; set; }
        public virtual DbSet<DOMINGOSTRABAJADOS> DOMINGOSTRABAJADOS { get; set; }
        public virtual DbSet<LOGTRABAJADOR> LOGTRABAJADOR { get; set; }
        public virtual DbSet<USUARIO_ANDROID> USUARIO_ANDROID { get; set; }
        public virtual DbSet<DISPOSITIVO_ANDROID> DISPOSITIVO_ANDROID { get; set; }
        public virtual DbSet<SOLICITUD_ANDROID> SOLICITUD_ANDROID { get; set; }
    
        public virtual ObjectResult<PERMISO_USUARIO_Result> PERMISO_USUARIO(string eMPRESA, string uSUARIO)
        {
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PERMISO_USUARIO_Result>("PERMISO_USUARIO", eMPRESAParameter, uSUARIOParameter);
        }
    
        public virtual ObjectResult<string> GENERA_CLAVE_VALIDACION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GENERA_CLAVE_VALIDACION");
        }
    
        public virtual ObjectResult<VALIDA_HASH_Result> VALIDA_HASH(string hASHSTRING, string tIPO, string cLAVE, string rUT_TRABAJADOR)
        {
            var hASHSTRINGParameter = hASHSTRING != null ?
                new ObjectParameter("HASHSTRING", hASHSTRING) :
                new ObjectParameter("HASHSTRING", typeof(string));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            var rUT_TRABAJADORParameter = rUT_TRABAJADOR != null ?
                new ObjectParameter("RUT_TRABAJADOR", rUT_TRABAJADOR) :
                new ObjectParameter("RUT_TRABAJADOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VALIDA_HASH_Result>("VALIDA_HASH", hASHSTRINGParameter, tIPOParameter, cLAVEParameter, rUT_TRABAJADORParameter);
        }
    
        public virtual ObjectResult<TRABAJADORESVIGENTES_Result> TRABAJADORESVIGENTES(string eMP)
        {
            var eMPParameter = eMP != null ?
                new ObjectParameter("EMP", eMP) :
                new ObjectParameter("EMP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TRABAJADORESVIGENTES_Result>("TRABAJADORESVIGENTES", eMPParameter);
        }
    
        public virtual ObjectResult<NOTIFICACIONES_PENDIENTES_TRABAJADOR_Result> NOTIFICACIONES_PENDIENTES_TRABAJADOR(string tRABAJADOR)
        {
            var tRABAJADORParameter = tRABAJADOR != null ?
                new ObjectParameter("TRABAJADOR", tRABAJADOR) :
                new ObjectParameter("TRABAJADOR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NOTIFICACIONES_PENDIENTES_TRABAJADOR_Result>("NOTIFICACIONES_PENDIENTES_TRABAJADOR", tRABAJADORParameter);
        }
    
        public virtual ObjectResult<JVC_DOTACION_Result> JVC_DOTACION(Nullable<int> fAENA, Nullable<System.DateTime> fECHA, string eMPRESA)
        {
            var fAENAParameter = fAENA.HasValue ?
                new ObjectParameter("FAENA", fAENA) :
                new ObjectParameter("FAENA", typeof(int));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JVC_DOTACION_Result>("JVC_DOTACION", fAENAParameter, fECHAParameter, eMPRESAParameter);
        }
    
        public virtual ObjectResult<JVC_MARCACIONES_Result> JVC_MARCACIONES(Nullable<System.DateTime> fECHAINICIO, Nullable<System.DateTime> fECHAFIN, Nullable<int> fAENA, string tRABAJADOR, string eMPRESA)
        {
            var fECHAINICIOParameter = fECHAINICIO.HasValue ?
                new ObjectParameter("FECHAINICIO", fECHAINICIO) :
                new ObjectParameter("FECHAINICIO", typeof(System.DateTime));
    
            var fECHAFINParameter = fECHAFIN.HasValue ?
                new ObjectParameter("FECHAFIN", fECHAFIN) :
                new ObjectParameter("FECHAFIN", typeof(System.DateTime));
    
            var fAENAParameter = fAENA.HasValue ?
                new ObjectParameter("FAENA", fAENA) :
                new ObjectParameter("FAENA", typeof(int));
    
            var tRABAJADORParameter = tRABAJADOR != null ?
                new ObjectParameter("TRABAJADOR", tRABAJADOR) :
                new ObjectParameter("TRABAJADOR", typeof(string));
    
            var eMPRESAParameter = eMPRESA != null ?
                new ObjectParameter("EMPRESA", eMPRESA) :
                new ObjectParameter("EMPRESA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JVC_MARCACIONES_Result>("JVC_MARCACIONES", fECHAINICIOParameter, fECHAFINParameter, fAENAParameter, tRABAJADORParameter, eMPRESAParameter);
        }
    }
}
