//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESGLOSEVACACION
    {
        public int ID_PERIODO { get; set; }
        public int ID_TIPO { get; set; }
        public double DIAS { get; set; }
    
        public virtual TIPOVACACION TIPOVACACION { get; set; }
        public virtual VACACIONES VACACIONES { get; set; }
    }
}
