//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISPOSITIVO_ANDROID
    {
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string ID_DISPOSITIVO { get; set; }
        public string MONITOREADO { get; set; }
        public int TIEMPO_MONITOR { get; set; }
        public Nullable<System.DateTime> ULTIMO_PING { get; set; }
        public bool NOTIFICAR { get; set; }
        public Nullable<System.DateTime> PENULTIMO_PING { get; set; }
    }
}
