//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOS_CLOUD
    {
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string ARCHIVO { get; set; }
        public string EXTENSION { get; set; }
        public Nullable<System.DateTime> FINICIO { get; set; }
        public System.DateTime FTERMINO { get; set; }
        public System.DateTime FSUBIDA { get; set; }
        public string USUARIO { get; set; }
        public string EMPRESA { get; set; }
        public double TAMANO { get; set; }
        public string NOTIFICA_TERMINO { get; set; }
        public string TRABAJADOR { get; set; }
        public byte[] DOC { get; set; }
        public string MAIL_NOTIFICA { get; set; }
        public Nullable<int> DIAS_NOTIFICACION1 { get; set; }
        public Nullable<int> DIAS_NOTIFICACION2 { get; set; }
        public string S3_BUCKET { get; set; }
        public string S3_DIRECTORIO { get; set; }
        public string S3_DOCUEMNTO { get; set; }
    
        public virtual EMPRESA EMPRESA1 { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
