//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOMINGOSTRABAJADOS
    {
        public int correl { get; set; }
        public int nro_solici { get; set; }
        public string nrt_ruttr { get; set; }
        public System.DateTime fec_solic { get; set; }
        public Nullable<int> nro_dias { get; set; }
        public Nullable<System.DateTime> fec_origen { get; set; }
        public Nullable<System.DateTime> fec_usado { get; set; }
        public string flg_estado { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fec_autori { get; set; }
    }
}
