//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESA()
        {
            this.BANCOEMPRESA = new HashSet<BANCOEMPRESA>();
            this.CARGOEMPRESA = new HashSet<CARGOEMPRESA>();
            this.CCOSTO = new HashSet<CCOSTO>();
            this.FORMHEXTRA = new HashSet<FORMHEXTRA>();
            this.NOTAS = new HashSet<NOTAS>();
            this.PERMISO = new HashSet<PERMISO>();
            this.SOLICITUDSERVICIO = new HashSet<SOLICITUDSERVICIO>();
            this.VALIDACIONES = new HashSet<VALIDACIONES>();
            this.VEHICULO = new HashSet<VEHICULO>();
            this.SOLICITUDPERMANENTESERVICIO = new HashSet<SOLICITUDPERMANENTESERVICIO>();
            this.ACREDITACION = new HashSet<ACREDITACION>();
            this.SERVICIOEMPRESA = new HashSet<SERVICIOEMPRESA>();
            this.SERVICIOCONTRATADO = new HashSet<SERVICIOCONTRATADO>();
            this.SOLICITUDVACACIONES = new HashSet<SOLICITUDVACACIONES>();
            this.PARAMETRODIACOMPENSADO = new HashSet<PARAMETRODIACOMPENSADO>();
            this.COLACIONESDIARIAS = new HashSet<COLACIONESDIARIAS>();
            this.DOCUMENTOS_CLOUD = new HashSet<DOCUMENTOS_CLOUD>();
            this.FAENA = new HashSet<FAENA>();
            this.CONTRATO = new HashSet<CONTRATO>();
            this.ARCHIVOS_EMPRESA = new HashSet<ARCHIVOS_EMPRESA>();
            this.PERMISO_V2 = new HashSet<PERMISO_V2>();
        }
    
        public string RUT { get; set; }
        public string IDSISTEMA { get; set; }
        public string NFANTASIA { get; set; }
        public string RSOCIAL { get; set; }
        public string GIRO { get; set; }
        public string DIRECCION { get; set; }
        public int REGION { get; set; }
        public int CIUDAD { get; set; }
        public int COMUNA { get; set; }
        public byte[] LOGO { get; set; }
        public string NREPLEGAL { get; set; }
        public string RUTREPLEGAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public string URL_LOGO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANCOEMPRESA> BANCOEMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARGOEMPRESA> CARGOEMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCOSTO> CCOSTO { get; set; }
        public virtual CIUDAD CIUDAD1 { get; set; }
        public virtual COMUNA COMUNA1 { get; set; }
        public virtual REGION REGION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FORMHEXTRA> FORMHEXTRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTAS> NOTAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISO> PERMISO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDSERVICIO> SOLICITUDSERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALIDACIONES> VALIDACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDPERMANENTESERVICIO> SOLICITUDPERMANENTESERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACREDITACION> ACREDITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOEMPRESA> SERVICIOEMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOCONTRATADO> SERVICIOCONTRATADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDVACACIONES> SOLICITUDVACACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARAMETRODIACOMPENSADO> PARAMETRODIACOMPENSADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLACIONESDIARIAS> COLACIONESDIARIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTOS_CLOUD> DOCUMENTOS_CLOUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAENA> FAENA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARCHIVOS_EMPRESA> ARCHIVOS_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISO_V2> PERMISO_V2 { get; set; }
    }
}
