//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVIOMAIL
    {
        public int ID { get; set; }
        public int IDCONTACTO { get; set; }
        public string TIPOENVIO { get; set; }
        public Nullable<int> NOTIFICACION_1 { get; set; }
        public Nullable<int> NOTIFICACION_2 { get; set; }
    
        public virtual CARGOEMPRESA CARGOEMPRESA { get; set; }
    }
}
