//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMENMEDICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAMENMEDICO()
        {
            this.DESCBATERIAEXAMENES = new HashSet<DESCBATERIAEXAMENES>();
        }
    
        public int ID { get; set; }
        public string PERSONA { get; set; }
        public System.DateTime FECHA { get; set; }
        public int INSTITUCION { get; set; }
        public bool RESULTADO { get; set; }
        public System.DateTime FVENCIMIENTO { get; set; }
        public string OBSERVACIONES { get; set; }
        public byte[] PDF { get; set; }
        public string VALIDOPOR { get; set; }
        public Nullable<System.DateTime> FECHAVALIDO { get; set; }
    
        public virtual INSTITUCION INSTITUCION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESCBATERIAEXAMENES> DESCBATERIAEXAMENES { get; set; }
        public virtual PERSONA PERSONA1 { get; set; }
    }
}
