//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAENA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAENA()
        {
            this.ABASTECIMIENTOAGUA = new HashSet<ABASTECIMIENTOAGUA>();
            this.ACTEXTRAPROGRAMATICA = new HashSet<ACTEXTRAPROGRAMATICA>();
            this.CALIBRACIONEQUIPOS = new HashSet<CALIBRACIONEQUIPOS>();
            this.CERTIFICACION = new HashSet<CERTIFICACION>();
            this.CERTIFICACIONUPDATE = new HashSet<CERTIFICACIONUPDATE>();
            this.COLACIONESDIARIAS = new HashSet<COLACIONESDIARIAS>();
            this.COLACIONESHHEE = new HashSet<COLACIONESHHEE>();
            this.FINIQUITO = new HashSet<FINIQUITO>();
            this.LIMPIEZABANHOS = new HashSet<LIMPIEZABANHOS>();
            this.MOVILIZACIONHHEE = new HashSet<MOVILIZACIONHHEE>();
            this.TURNOCOLACION = new HashSet<TURNOCOLACION>();
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public int ID { get; set; }
        public string IDSISTEMA { get; set; }
        public string EMPRESA { get; set; }
        public System.DateTime FINICIO { get; set; }
        public Nullable<System.DateTime> FTERMINO { get; set; }
        public string DIRECCION { get; set; }
        public int CIUDAD { get; set; }
        public int COMUNA { get; set; }
        public string NUMCONTRATO { get; set; }
        public int INSTALACIONESMANDANTE { get; set; }
        public string DESCRIPCION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABASTECIMIENTOAGUA> ABASTECIMIENTOAGUA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTEXTRAPROGRAMATICA> ACTEXTRAPROGRAMATICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CALIBRACIONEQUIPOS> CALIBRACIONEQUIPOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERTIFICACION> CERTIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERTIFICACIONUPDATE> CERTIFICACIONUPDATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLACIONESDIARIAS> COLACIONESDIARIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLACIONESHHEE> COLACIONESHHEE { get; set; }
        public virtual EMPRESA EMPRESA1 { get; set; }
        public virtual INSTALACIONES INSTALACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINIQUITO> FINIQUITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIMPIEZABANHOS> LIMPIEZABANHOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVILIZACIONHHEE> MOVILIZACIONHHEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TURNOCOLACION> TURNOCOLACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
    }
}
