//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINIQUITO
    {
        public int ID { get; set; }
        public int FAENA { get; set; }
        public string TRABAJADOR { get; set; }
        public System.DateTime FTERMINO_CONTRATO { get; set; }
        public double MONTOBRUTO_MES1 { get; set; }
        public double MONTOBRUTO_MES2 { get; set; }
        public double MONTOBRUTO_MES3 { get; set; }
        public double MONTO_MES_AVISO { get; set; }
        public double MONTOIMPONIBLE_MES1 { get; set; }
        public double MONTOIMPONIBLE_MES2 { get; set; }
        public double MONTOIMPONIBLE_MES3 { get; set; }
        public Nullable<double> VACACIONES_TOMADAS { get; set; }
        public Nullable<double> VACACIONES_PENDIENTES { get; set; }
        public Nullable<double> MONTO_VACACIONES_PROP { get; set; }
        public Nullable<double> DIAS_FESTIVOS { get; set; }
        public Nullable<double> MONTO_DIA_2_5 { get; set; }
        public Nullable<double> MONTO_2_5 { get; set; }
        public Nullable<double> DIAS_INHABILES { get; set; }
        public double MOTNO_AFC { get; set; }
        public double MONTO_IAS { get; set; }
        public Nullable<double> MONTO_INDEMNIZACION_VOL { get; set; }
        public string CAUSAL { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<double> TOTAL_FINIQUITO { get; set; }
        public string ARTICULO_CAUSAL { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE_SOLICITUD { get; set; }
        public int ESTADO { get; set; }
        public string USUARIO { get; set; }
        public byte[] PDF { get; set; }
        public Nullable<int> ID_CONTRATO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual FAENA FAENA1 { get; set; }
        public virtual CONTRATO CONTRATO { get; set; }
    }
}
