//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GESTIONORGANIZACIONAL
    {
        public string TRABAJADOR { get; set; }
        public string NIVELESTUDIO { get; set; }
        public string BENEFICIARIOBECA { get; set; }
        public Nullable<bool> BENEFICIARIOSUBSIDIO { get; set; }
        public string DESCSUBSIDIO { get; set; }
        public string TIPODOMICILIO { get; set; }
        public string TENENCIA { get; set; }
        public Nullable<bool> LIBRETAAHORRO { get; set; }
        public Nullable<int> ANTIGUEDADLIBRETA { get; set; }
        public Nullable<bool> PUEBLOINDIGENA { get; set; }
        public string DESCPUEBLOINDIGENA { get; set; }
        public Nullable<bool> REGISTROSOCIALHOGARES { get; set; }
        public Nullable<double> PORCENTAGEREGISTROSICOALHOGARES { get; set; }
        public Nullable<bool> DISCAPACIDAD { get; set; }
        public Nullable<bool> CREDENCIALDISCAPACIDAD { get; set; }
        public string TIPOSUBSIDIO { get; set; }
        public string TIPOESPECIFICOSUB { get; set; }
        public string BECA { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
