//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HASH_DOCUMENTOS
    {
        public int ID { get; set; }
        public string CLAVE { get; set; }
        public Nullable<System.DateTime> FECHA_FIRMA_EMPRESA { get; set; }
        public Nullable<System.DateTime> FECHA_FIRMA_TRABAJADOR { get; set; }
        public Nullable<System.DateTime> FECHA_FINAL { get; set; }
        public string TABLA_DOCUMENTO { get; set; }
        public string HASH_FIRMA_EMPRESA { get; set; }
        public string HASH_FIRMA_TRABAJADOR { get; set; }
        public string HASH_DOCUMENTO_FINAL { get; set; }
        public int ID_DOCUMENTO { get; set; }
        public string USUARIO_FIRMA_EMPRESA { get; set; }
        public string RUT_FIRMA_TRABAJADOR { get; set; }
        public string OBSERVACION { get; set; }
        public string HASH_DOCUMENTO_CERRADO { get; set; }
        public string CLAVE_VALIDACION { get; set; }
        public string HASH_PREVIO { get; set; }
        public string HASH_ACTUAL { get; set; }
        public Nullable<int> ID_PREVIO { get; set; }
        public Nullable<bool> FIRMA_ELECTRONICA { get; set; }
    }
}
