//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTALACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSTALACIONES()
        {
            this.FAENA = new HashSet<FAENA>();
        }
    
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string DIRECCION { get; set; }
        public int CIUDAD { get; set; }
        public int COMUNA { get; set; }
        public int MANDANTE { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual MANDANTE MANDANTE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAENA> FAENA { get; set; }
    }
}
