//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ACEPTATIEMPO
    {
        public int LID { get; set; }
        public string LESTADO { get; set; }
        public string LACCION { get; set; }
        public System.DateTime LFECHACAMBIO { get; set; }
        public string LCORREO { get; set; }
        public string LTOKEN { get; set; }
    }
}
