//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_MARCACIONES
    {
        public int ID { get; set; }
        public string EMPRESA { get; set; }
        public string TRABAJADOR { get; set; }
        public System.DateTime MARCA_ORIGINAL { get; set; }
        public string TIPO_MARCA_ORIGINAL { get; set; }
        public Nullable<System.DateTime> MARCA_NUEVA { get; set; }
        public string TIPO_MARCA_NUEVA { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA_MOD { get; set; }
        public string ACCION { get; set; }
    }
}
