//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANDANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MANDANTE()
        {
            this.INSTALACIONES = new HashSet<INSTALACIONES>();
            this.ACREDITACION = new HashSet<ACREDITACION>();
        }
    
        public int ID { get; set; }
        public string DESCRIPCION { get; set; }
        public string DIRECCION { get; set; }
        public int CIUDAD { get; set; }
        public Nullable<int> COMUNA { get; set; }
        public string RUT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSTALACIONES> INSTALACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACREDITACION> ACREDITACION { get; set; }
        public virtual SETUPMANDANTE SETUPMANDANTE { get; set; }
    }
}
