//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANOOBRADIRECTA
    {
        public int ID { get; set; }
        public string EMPRESA { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public int CARGO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<bool> FINALIZADO { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual CARGO CARGO1 { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
