//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICACION
    {
        public int ID { get; set; }
        public string TIPO { get; set; }
        public System.DateTime FECHA { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<bool> GYC { get; set; }
        public Nullable<bool> NOTIFTRABAJADOR { get; set; }
        public Nullable<bool> NOTIFEMPRESA { get; set; }
        public string TRABAJADOR { get; set; }
        public string EMPRESA { get; set; }
        public string USUARIO { get; set; }
        public string TABLA { get; set; }
        public int IDTABLA { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public Nullable<bool> VISTO { get; set; }
    
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
