//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIA
    {
        public int ID { get; set; }
        public string TITULO { get; set; }
        public string CONTENIDO { get; set; }
        public string AUTOR { get; set; }
        public byte[] IMAGEN { get; set; }
        public string SERVICIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
