//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO_V2
    {
        public int ID { get; set; }
        public int PERMISO { get; set; }
        public string RUT { get; set; }
        public string EMPRESA { get; set; }
        public int SERVICIO { get; set; }
    
        public virtual EMPRESA EMPRESA1 { get; set; }
        public virtual SERVICIO SERVICIO1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual DESCPERMISO DESCPERMISO { get; set; }
    }
}
