//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOINASISTENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERMISOINASISTENCIA()
        {
            this.COMPENSADO_UTILIZADO = new HashSet<COMPENSADO_UTILIZADO>();
        }
    
        public int ID { get; set; }
        public string TRABAJADOR { get; set; }
        public System.DateTime FINICIO { get; set; }
        public System.DateTime FTERMINO { get; set; }
        public Nullable<bool> GOCESUELDO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPENSADO_UTILIZADO> COMPENSADO_UTILIZADO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
