//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONA()
        {
            this.ACREDITACION = new HashSet<ACREDITACION>();
            this.ATENCIONORGANIZACIONAL = new HashSet<ATENCIONORGANIZACIONAL>();
            this.ATENCIONORGANIZACIONALONLINE = new HashSet<ATENCIONORGANIZACIONALONLINE>();
            this.CARTAAMONESTACION = new HashSet<CARTAAMONESTACION>();
            this.CHARLASEGURIDAD = new HashSet<CHARLASEGURIDAD>();
            this.DIASCOMPENSADOS = new HashSet<DIASCOMPENSADOS>();
            this.EXAMENMEDICO = new HashSet<EXAMENMEDICO>();
            this.GRUPOFAMILIAR = new HashSet<GRUPOFAMILIAR>();
            this.HHEE = new HashSet<HHEE>();
            this.LICENCIAMEDICA = new HashSet<LICENCIAMEDICA>();
            this.MARCACIONRELOJ = new HashSet<MARCACIONRELOJ>();
            this.PERMISOINASISTENCIA = new HashSet<PERMISOINASISTENCIA>();
            this.REGISTRORELOJ = new HashSet<REGISTRORELOJ>();
            this.REMUNERACION = new HashSet<REMUNERACION>();
            this.SOLICITUDSERVICIO = new HashSet<SOLICITUDSERVICIO>();
            this.VACACIONES = new HashSet<VACACIONES>();
            this.VALIDACIONES = new HashSet<VALIDACIONES>();
            this.FINIQUITO = new HashSet<FINIQUITO>();
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public string DIRECCION { get; set; }
        public int REGION { get; set; }
        public int CIUDAD { get; set; }
        public int COMUNA { get; set; }
        public System.DateTime FNACIMIENTO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string SEXO { get; set; }
        public int TELEFONO1 { get; set; }
        public Nullable<int> TELEFONO2 { get; set; }
        public string CORREO { get; set; }
        public Nullable<int> BANCO { get; set; }
        public int TCUENTA { get; set; }
        public string NCUENTA { get; set; }
        public int ECIVIL { get; set; }
        public int NHIJOS { get; set; }
        public string NCONTACTOEM { get; set; }
        public int TCONTACTOEM { get; set; }
        public int SALUD { get; set; }
        public Nullable<double> ADICIONALSALUD { get; set; }
        public int PREVISION { get; set; }
        public Nullable<double> APV { get; set; }
        public Nullable<double> AHORRO { get; set; }
        public string EMPRESAACTUAL { get; set; }
        public string ESTADOCONTRATUAL { get; set; }
        public byte[] FOTO { get; set; }
        public Nullable<int> OMONTO1 { get; set; }
        public Nullable<int> OMONTO2 { get; set; }
        public Nullable<int> OMONTO3 { get; set; }
        public string DMONTO1 { get; set; }
        public string DMONTO2 { get; set; }
        public string DMONTO3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACREDITACION> ACREDITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENCIONORGANIZACIONAL> ATENCIONORGANIZACIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATENCIONORGANIZACIONALONLINE> ATENCIONORGANIZACIONALONLINE { get; set; }
        public virtual BANCO BANCO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARTAAMONESTACION> CARTAAMONESTACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHARLASEGURIDAD> CHARLASEGURIDAD { get; set; }
        public virtual CIUDAD CIUDAD1 { get; set; }
        public virtual COMUNA COMUNA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIASCOMPENSADOS> DIASCOMPENSADOS { get; set; }
        public virtual ENROLL ENROLL { get; set; }
        public virtual EPP EPP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMENMEDICO> EXAMENMEDICO { get; set; }
        public virtual GESTIONORGANIZACIONAL GESTIONORGANIZACIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPOFAMILIAR> GRUPOFAMILIAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HHEE> HHEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICENCIAMEDICA> LICENCIAMEDICA { get; set; }
        public virtual LOGINTRABAJADOR LOGINTRABAJADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARCACIONRELOJ> MARCACIONRELOJ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISOINASISTENCIA> PERMISOINASISTENCIA { get; set; }
        public virtual PREVISION PREVISION1 { get; set; }
        public virtual REGION REGION1 { get; set; }
        public virtual SALUD SALUD1 { get; set; }
        public virtual TIPOCUENTA TIPOCUENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRORELOJ> REGISTRORELOJ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REMUNERACION> REMUNERACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLICITUDSERVICIO> SOLICITUDSERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VACACIONES> VACACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VALIDACIONES> VALIDACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINIQUITO> FINIQUITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
    }
}
