//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remebene
    {
        public int correl { get; set; }
        public string nrt_ruttr { get; set; }
        public int nrt_benef { get; set; }
        public string dgv_benef { get; set; }
        public string app_benef { get; set; }
        public string apm_benef { get; set; }
        public string nom_benef { get; set; }
        public string flg_sexo { get; set; }
        public System.DateTime fec_nacim { get; set; }
        public string cod_paren { get; set; }
        public string tip_reten { get; set; }
        public string cod_aplica { get; set; }
        public Nullable<System.DateTime> fec_inicio { get; set; }
        public Nullable<System.DateTime> fec_termi { get; set; }
        public string rut_empr { get; set; }
    }
}
