//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remelabo
    {
        public int correl { get; set; }
        public string nrt_ruttr { get; set; }
        public System.DateTime fec_ingre { get; set; }
        public string cod_roltr { get; set; }
        public string cod_cenre { get; set; }
        public Nullable<System.DateTime> fec_indem { get; set; }
        public string cod_categ { get; set; }
        public Nullable<System.DateTime> fec_categ { get; set; }
        public Nullable<int> mto_sueldo { get; set; }
        public string cod_sindic { get; set; }
        public Nullable<System.DateTime> fec_sindic { get; set; }
        public string cod_ine { get; set; }
        public string cod_corfo { get; set; }
        public string cod_cargo { get; set; }
        public Nullable<System.DateTime> fec_cargo { get; set; }
        public string flg_tipcon { get; set; }
        public string cod_horar { get; set; }
        public string flg_suple { get; set; }
        public string rut_empr { get; set; }
    }
}
