//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remefami
    {
        public int correl { get; set; }
        public string nrt_ruttr { get; set; }
        public string nrt_rutcf { get; set; }
        public string nom_appcf { get; set; }
        public string nom_apmcf { get; set; }
        public string nom_nomcf { get; set; }
        public string flg_sexo { get; set; }
        public System.DateTime fec_nacim { get; set; }
        public string cod_paren { get; set; }
        public string flg_duplo { get; set; }
        public string cod_becas { get; set; }
        public string cod_estud { get; set; }
        public Nullable<int> nrt_benef { get; set; }
        public Nullable<System.DateTime> fec_inicio { get; set; }
        public Nullable<System.DateTime> fec_termin { get; set; }
        public string rut_empr { get; set; }
    }
}
