//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remehabe
    {
        public int correl { get; set; }
        public int cod_haber { get; set; }
        public string gls_haber { get; set; }
        public string flg_impon { get; set; }
        public string flg_tribut { get; set; }
        public Nullable<short> num_meses { get; set; }
        public string flg_garant { get; set; }
        public string flg_reten { get; set; }
        public string flg_calcul { get; set; }
        public string flg_tiempo { get; set; }
        public string flg_deduci { get; set; }
        public string flg_blicen { get; set; }
        public string flg_bhextra { get; set; }
        public string flg_bindem { get; set; }
        public string flg_brenvar { get; set; }
        public string rut_empr { get; set; }
    }
}
