//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remecarg
    {
        public int correl { get; set; }
        public string cod_cargo { get; set; }
        public string gls_cargo { get; set; }
        public int nro_resol { get; set; }
        public System.DateTime fec_creaci { get; set; }
        public string cod_roltr { get; set; }
        public string cod_tipes { get; set; }
        public string cod_profes { get; set; }
        public string cod_ambien { get; set; }
        public string rut_empr { get; set; }
    }
}
