//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remepers
    {
        public int correl { get; set; }
        public string nrt_ruttr { get; set; }
        public string dgv_ruttr { get; set; }
        public string nom_appat { get; set; }
        public string nom_apmat { get; set; }
        public string nom_nomtr { get; set; }
        public System.DateTime fec_nacim { get; set; }
        public string flg_sexo { get; set; }
        public string flg_estci { get; set; }
        public string gls_direcc { get; set; }
        public string gls_ciudad { get; set; }
        public string cod_nacion { get; set; }
        public string rut_empr { get; set; }
    }
}
