//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remedein
    {
        public int correl { get; set; }
        public string nrt_ruttr { get; set; }
        public short nro_correl { get; set; }
        public int cod_descu { get; set; }
        public string flg_afecta { get; set; }
        public Nullable<int> cod_haber { get; set; }
        public string cod_pago { get; set; }
        public string flg_forde { get; set; }
        public decimal val_descu { get; set; }
        public System.DateTime fec_desde { get; set; }
        public System.DateTime fec_hasta { get; set; }
        public System.DateTime fec_ingre { get; set; }
        public Nullable<short> num_pagin { get; set; }
        public Nullable<int> nrt_rutbe { get; set; }
        public string rut_empr { get; set; }
    }
}
