//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remeasis
    {
        public int correl { get; set; }
        public string nrt_ruttr { get; set; }
        public System.DateTime fec_asist { get; set; }
        public string cod_inasi { get; set; }
        public Nullable<int> cnt_inasi { get; set; }
        public Nullable<decimal> hrs_sob1 { get; set; }
        public Nullable<decimal> hrs_sob2 { get; set; }
        public Nullable<decimal> hrs_sob3 { get; set; }
        public Nullable<int> dia_colac { get; set; }
        public Nullable<int> hrs_colac { get; set; }
        public Nullable<int> dia_movil { get; set; }
        public string rut_empr { get; set; }
    }
}
