//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remeresu
    {
        public int correl { get; set; }
        public string nrt_ruttr { get; set; }
        public string cod_pago { get; set; }
        public int cod_conce { get; set; }
        public string gls_conce { get; set; }
        public Nullable<decimal> cnt_conce { get; set; }
        public Nullable<decimal> val_conce { get; set; }
        public Nullable<decimal> mto_pagar { get; set; }
        public Nullable<System.DateTime> fec_pago { get; set; }
        public string rut_empr { get; set; }
    }
}
