//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remedesc
    {
        public int correl { get; set; }
        public Nullable<int> Cod_descu { get; set; }
        public string gls_descu { get; set; }
        public Nullable<short> cod_prior { get; set; }
        public Nullable<int> min_descu { get; set; }
        public Nullable<int> max_descu { get; set; }
        public string rut_empr { get; set; }
    }
}
