//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class remepage
    {
        public int correl { get; set; }
        public string nom_tabla { get; set; }
        public string cod_param { get; set; }
        public string gls_param { get; set; }
        public string val_param { get; set; }
        public Nullable<System.DateTime> fec_param { get; set; }
        public Nullable<System.DateTime> fec_inicio { get; set; }
        public Nullable<System.DateTime> fec_termin { get; set; }
        public string rut_empr { get; set; }
    }
}
