//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rhuedias
    {
        public int correl { get; set; }
        public string cod_horar { get; set; }
        public Nullable<int> dias_legal { get; set; }
        public Nullable<int> dias_contr { get; set; }
        public Nullable<int> dias_admin { get; set; }
        public Nullable<int> dias_faena { get; set; }
        public Nullable<int> dias_especi { get; set; }
        public Nullable<int> dias_otros { get; set; }
        public System.DateTime fec_inicio { get; set; }
        public string rut_empr { get; set; }
    }
}
