//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rhueempr
    {
        public int correl { get; set; }
        public string cod_empresa { get; set; }
        public string cod_gerencia { get; set; }
        public string cod_unidad { get; set; }
        public string cod_seccion { get; set; }
        public string cod_division { get; set; }
        public string cod_subdiv { get; set; }
        public string cod_cenres { get; set; }
        public string rut_empr { get; set; }
    }
}
