//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINDICATOTRABAJADOR
    {
        public int correl { get; set; }
        public string nrt_ruttr { get; set; }
        public string cod_sindi { get; set; }
        public Nullable<System.DateTime> fec_afili { get; set; }
    }
}
