//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_ANDROID
    {
        public int id { get; set; }
        public int correl { get; set; }
        public string nrt_ruttr { get; set; }
        public string flg_tipo { get; set; }
        public System.DateTime fec_desde { get; set; }
        public Nullable<System.DateTime> fec_hasta { get; set; }
        public Nullable<int> nro_dias { get; set; }
        public System.DateTime fec_proce { get; set; }
        public string flg_estado { get; set; }
    }
}
