//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public int ID { get; set; }
        public int CONVERSACION { get; set; }
        public string TRABAJADOR { get; set; }
        public string MENSAJE { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string TEMA { get; set; }
        public string POSTER { get; set; }
        public string CATEGORIA { get; set; }
        public bool VISTO { get; set; }
    }
}
