//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABAJADORESNOACREDITADOS
    {
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public string DIRECCION { get; set; }
        public int REGION { get; set; }
        public int CIUDAD { get; set; }
        public int COMUNA { get; set; }
        public System.DateTime FNACIMIENTO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string SEXO { get; set; }
        public int TELEFONO1 { get; set; }
        public Nullable<int> TELEFONO2 { get; set; }
        public string CORREO { get; set; }
        public Nullable<int> BANCO { get; set; }
        public int TCUENTA { get; set; }
        public string NCUENTA { get; set; }
        public int ECIVIL { get; set; }
        public int NHIJOS { get; set; }
        public string NCONTACTOEM { get; set; }
        public int TCONTACTOEM { get; set; }
        public int SALUD { get; set; }
        public Nullable<double> ADICIONALSALUD { get; set; }
        public int PREVISION { get; set; }
        public Nullable<double> APV { get; set; }
        public Nullable<double> AHORRO { get; set; }
        public string EMPRESAACTUAL { get; set; }
        public string ESTADOCONTRATUAL { get; set; }
        public byte[] FOTO { get; set; }
        public Nullable<int> OMONTO1 { get; set; }
        public Nullable<int> OMONTO2 { get; set; }
        public Nullable<int> OMONTO3 { get; set; }
        public string DMONTO1 { get; set; }
        public string DMONTO2 { get; set; }
        public string DMONTO3 { get; set; }
    }
}
