//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurnoTrabajador
    {
        public long IdTurnoTrabajador { get; set; }
        public Nullable<int> IdTurno { get; set; }
        public string RutTrabajador { get; set; }
        public Nullable<System.DateTime> FechaInicioTurno { get; set; }
        public Nullable<System.DateTime> FechaTerminoTurno { get; set; }
        public Nullable<short> SecuenciaIngreso { get; set; }
        public Nullable<int> HorasSemana { get; set; }
        public Nullable<int> MinutosSemana { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> EsVigente { get; set; }
    
        public virtual Turno Turno { get; set; }
    }
}
