//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNOCOLACION
    {
        public int ID { get; set; }
        public int FAENA { get; set; }
        public int ID_TURNO { get; set; }
        public int DIASEMANA { get; set; }
        public double HCOLACION { get; set; }
    
        public virtual FAENA FAENA1 { get; set; }
    }
}
