//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turno()
        {
            this.TurnoDetalle = new HashSet<TurnoDetalle>();
            this.TurnoTrabajador = new HashSet<TurnoTrabajador>();
        }
    
        public int IdTurno { get; set; }
        public string CodigoInterno { get; set; }
        public string CodigoTurno { get; set; }
        public Nullable<short> DiasTrabajo { get; set; }
        public Nullable<short> DiasDescanso { get; set; }
        public Nullable<short> TotalSecuencia { get; set; }
        public Nullable<short> TotalCiclos { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<bool> EsVigente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnoDetalle> TurnoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnoTrabajador> TurnoTrabajador { get; set; }
    }
}
