//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_ANDROID
    {
        public int ID { get; set; }
        public string RUT { get; set; }
        public string CONTRASEÑA { get; set; }
        public Nullable<int> DISPOSITIVO { get; set; }
        public string TOKEN { get; set; }
        public int ESTADO { get; set; }
        public string TIPO { get; set; }
        public Nullable<bool> TOUCHLESS { get; set; }
    }
}
