//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALIDACIONES
    {
        public int VALIDACION { get; set; }
        public int CONTRATO { get; set; }
        public string EMPRESA { get; set; }
        public string RUT { get; set; }
        public System.DateTime FECHAVALIDA { get; set; }
        public System.DateTime FECHAVENCE { get; set; }
        public Nullable<bool> ESTADO { get; set; }
        public string OBS { get; set; }
        public string VALIDOPOR { get; set; }
        public Nullable<System.DateTime> FECHAVALIDO { get; set; }
        public string PDF { get; set; }
    
        public virtual DESCVALIDACION DESCVALIDACION { get; set; }
        public virtual EMPRESA EMPRESA1 { get; set; }
        public virtual PERSONA PERSONA { get; set; }
        public virtual CONTRATO CONTRATO1 { get; set; }
    }
}
