//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GYCEmpresa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public int ID { get; set; }
        public string PATENTE { get; set; }
        public int MARCA { get; set; }
        public int MODELO { get; set; }
        public int CARROCERIA { get; set; }
        public string MOTOR { get; set; }
        public string COLOR { get; set; }
        public int ANHO { get; set; }
        public string EMPRESA { get; set; }
    
        public virtual CARROCERIA CARROCERIA1 { get; set; }
        public virtual EMPRESA EMPRESA1 { get; set; }
        public virtual MARCA MARCA1 { get; set; }
        public virtual MODELO MODELO1 { get; set; }
    }
}
